### PR TITLE
Pricinpal design-teardown

### PR DESCRIPTION
**Pull request by sipe-daniel**
design-teardown is a simple project and consisted to build a page which matches wich apart the website for a popular design magazine called the Smashing Magazine. 

**_I received permission to work alone on this project_**

### CODE REVIEW

**Review by christianotieno — COMMENTED** [review]
# ATTENTION 🔔 
Hey @sipe-daniel  :wave:
-

This is a [collaborative](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540025/) project, I noticed that you have worked alone on this project yourself. Any explanations why this is so?
##
- I am going to mark this CCR as invalid. Kindly provide reasons for working alone on this thank you!
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by sipe-daniel** [comment]
Hi! I work alone because I received permission for that,
you can ask @Willow (Student Success), @Greg (Student Success) or even @Andrea (Student Success). I have to work alone for all html/css project before to repair.

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey, @sipe-daniel 👋  Good job with the explanation.
-
You have done a splendid job! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
## REQUIRED:
- [x] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).
- [x] The CSS has not followed the DRY principle, There are currently,  a lot of repeated code in the CSS, please refactor the page's CSS. Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
- [x] All the elements and element's backgrounds and font colours should be grayscale colour (black, white or any shade of grey), this rule also applies to images as well ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/design_teardown/grayscale_requirement.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/design-teardown)). 
- [ ] ADD instructions to your README file on how to best clone and use your project.

## NOTE: 
In this project, you were required to produce a greyscale version of the website you were cloning, the colouring was not necessary. Please refer to the project specification for this. 
##
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by sipe-daniel** [comment]
Please I don't understand your last point, I don't know but it's a simple page, not a great project. I don't know how someone can use my project and concerning the best way to clone I think I already said I used HTML and CSS for this project. There are many ways to build this project and I don't have the pretension to say the best manner to clone this project. Someone can use for instance position, float in CSS or bootstrap, skeleton.

**Review by lucasmazo32 — APPROVED** [review]
# Project approved :rocket:

#### Great job!

#### Your project looks great!

### You can go ahead and merge this pull request!

### Happy coding! :computer:

## Lucas Mazo

**Pull request merged**
